export const API_ROUTES = {
  agent: {
    respond: "/api/agent/respond",
  },
  board: {
    promptText: "/api/board/prompt-text",
  },
  chat: {
    completions: "/api/chat/completions",
  },
  media: {
    audioDownload: "/api/media/audio-download",
    cancel: "/api/media/cancel",
    generateAudio: "/api/media/generate-audio",
    generateAudioWorkflow: "/api/media/generate-audio-workflow",
    generateImage: "/api/media/generate-image",
    generateVideo: "/api/media/generate-video",
    imageDownload: "/api/media/image-download",
    referenceImage: "/api/media/reference-image",
    status: "/api/media/status",
    videoDownload: "/api/media/video-download",
  },
  prompts: {
    optimize: "/api/prompts/optimize",
  },
  resolve: {
    capabilities: "/api/resolve/capabilities",
    commands: "/api/resolve/commands",
    providerCredentials: "/api/resolve/provider-credentials",
  },
  storage: {
    localStatus: "/api/storage/local/status",
    teamBootstrap: "/api/storage/team/bootstrap",
    teamAssets: "/api/storage/team/assets",
    teamDataSummary: "/api/storage/team/data-summary",
    teamAssetLibrary: "/api/storage/team/asset-library",
    teamAssetLibraryItem: (itemId: string) => `/api/storage/team/asset-library/${encodeURIComponent(itemId)}`,
    teamGenerationTasks: "/api/storage/team/generation-tasks",
    teamGenerationTask: (taskId: string) => `/api/storage/team/generation-tasks/${encodeURIComponent(taskId)}`,
    teamBoards: "/api/storage/team/boards",
    teamBoard: (boardId: string) => `/api/storage/team/boards/${encodeURIComponent(boardId)}`,
    teamMembers: "/api/storage/team/members",
    teamMember: (userId: string) => `/api/storage/team/members/${encodeURIComponent(userId)}`,
    teamPromptTemplates: "/api/storage/team/prompt-templates",
    teamPromptTemplate: (templateId: string) => `/api/storage/team/prompt-templates/${encodeURIComponent(templateId)}`,
    teamBackup: "/api/storage/team/backup",
    teamSafetySnapshot: "/api/storage/team/safety-snapshot",
    teamVoiceProfiles: "/api/storage/team/voice-profiles",
    teamVoiceProfile: (profileId: string) => `/api/storage/team/voice-profiles/${encodeURIComponent(profileId)}`,
    teamProviderTargets: "/api/storage/team/provider-targets",
    teamProviderTarget: (targetId: string) => `/api/storage/team/provider-targets/${encodeURIComponent(targetId)}`,
    teamSettings: "/api/storage/team/settings",
    teamSetting: (key: string) => `/api/storage/team/settings/${encodeURIComponent(key)}`,
    teamSecrets: "/api/storage/team/secrets",
    teamSecret: (key: string) => `/api/storage/team/secrets/${encodeURIComponent(key)}`,
    teamAssetMedia: (assetId: string, options: { download?: boolean } = {}) => {
      const url = `/api/storage/team/assets/${encodeURIComponent(assetId)}/media`;
      return options.download ? `${url}?download=1` : url;
    },
    teamAsset: (assetId: string) => `/api/storage/team/assets/${encodeURIComponent(assetId)}`,
    teamHealth: "/api/storage/team/health",
    teamMediaMaintenance: "/api/storage/team/media-maintenance",
    teamMigrations: "/api/storage/team/migrations",
    teamSession: "/api/storage/team/session",
  },
  v1: {
    audioSpeech: "/v1/audio/speech",
    audioTranscriptions: "/v1/audio/transcriptions",
    chatCompletions: "/v1/chat/completions",
    imageEdits: "/v1/images/edits",
    imageGenerations: "/v1/images/generations",
    models: "/v1/models",
  },
} as const;
